#!/usr/bin/env python3
"""build_wiki_index.py — regenerate 05-knowledge/INDEX.md as an Obsidian map-of-content.

Walks the vault's knowledge + content directories, reads each markdown note's
frontmatter title (falling back to the filename), and emits an INDEX.md full of
[[wiki-links]] grouped by directory. Running this after every session keeps new
notes reachable in the Obsidian graph and gives GitHub a human-readable contents page.

Usage:  python3 scripts/build_wiki_index.py
"""

from __future__ import annotations
import os
import re
from datetime import date

# Directories to index, in display order.
SECTIONS = [
    ("05-knowledge/resources", "Research Reports & Resources"),
    ("05-knowledge/captures", "Telegram Captures"),
    ("05-knowledge/consolidated", "Frameworks & Synthesis"),
    ("05-knowledge/people", "People CRM"),
    ("05-knowledge/projects", "Project Knowledge"),
    ("05-knowledge/areas", "Areas"),
    ("03-professional/resume", "Resumes"),
    ("04-projects", "Projects"),
]

VAULT = os.getcwd()
OUT = os.path.join(VAULT, "05-knowledge", "INDEX.md")

FM_TITLE = re.compile(r"^title:\s*(.+?)\s*$", re.MULTILINE)


def read_title(path: str) -> str:
    """Return the frontmatter `title:` if present, else a humanized filename."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            head = f.read(1500)
    except OSError:
        head = ""
    if head.startswith("---"):
        block = head.split("---", 2)
        if len(block) >= 2:
            m = FM_TITLE.search(block[1])
            if m:
                return m.group(1).strip().strip("'\"")
    stem = os.path.splitext(os.path.basename(path))[0]
    return stem.replace("-", " ").replace("_", " ").title()


def wiki_name(path: str) -> str:
    """Obsidian resolves [[note]] by filename without extension."""
    return os.path.splitext(os.path.basename(path))[0]


def collect(rel_dir: str) -> list[tuple[str, str]]:
    base = os.path.join(VAULT, rel_dir)
    items: list[tuple[str, str]] = []
    if not os.path.isdir(base):
        return items
    for root, _dirs, files in os.walk(base):
        for fn in sorted(files):
            if fn.endswith(".md") and fn not in ("INDEX.md", ".gitkeep"):
                full = os.path.join(root, fn)
                items.append((read_title(full), wiki_name(full)))
    return sorted(items, key=lambda t: t[0].lower())


def main() -> None:
    lines = [
        "---",
        "title: Knowledge Index",
        "type: map-of-content",
        f"updated: {date.today().isoformat()}",
        "tags: [moc, index]",
        "---",
        "",
        "# 🧠 Knowledge Index",
        "",
        "_Auto-generated by `scripts/build_wiki_index.py` after each session. "
        "Every entry is an Obsidian `[[wiki-link]]`._",
        "",
    ]
    total = 0
    for rel_dir, heading in SECTIONS:
        items = collect(rel_dir)
        if not items:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for title, wiki in items:
            lines.append(f"- [[{wiki}|{title}]]")
            total += 1
        lines.append("")
    lines.append(f"> {total} notes indexed.")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"INDEX_UPDATED: {OUT} ({total} notes)")


if __name__ == "__main__":
    main()
